#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################

# Book settings
title: geo3D
author: arkriger

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  
# Add a launch button on a specific binder instance
launch_buttons:
  notebook_interface: "jupyterlab"
  binderhub_url: "https://mybinder.org/v2/gh/AdrianKriger/geo3D_wrkshp/HEAD"  # The URL for your BinderHub (e.g., https://mybinder.org)

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: geo3D_wrkshp.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - after/references.bib
sphinx:
   config:
        bibtex_reference_style: "author_year" 

# Information about where the book exists on the web
repository:
  url: https://github.com/AdrianKriger/geo3D_wrkshp  # Online location of your book
  path_to_book: tutorial  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
 
# html iframe images
#parse:
#  myst_enable_extensions:
#    - html_admonition
#    - html_image

