name: geo3D_wrkshp
channels:
- conda-forge             #- prioritizing conda-forge
#- defaults
dependencies:
- python=3.9
- fiona=1.9.4
- pandas=2.2.3
- gdal=3.7.3
- pyproj=3.6.1
- mapbox_earcut=1.0.1
- topojson=1.7
- jupyter-book
- jupyterlab
- matplotlib
- numpy
- shapely
- ghp-import
- pip
- pip:
  - triangle==20230923                                 #- python wrapper around Jonathan Richard Shewchuk's at rufat.be/triangle
  - cjio==0.7.3                                        #- python CLI to process and manipulate CityJSON files
  - overpass==0.7
  - openlocationcode==1.0.1                            #- google 'plus codes' at https://github.com/google/open-location-code
