name: geo3D_wrkshp
dependencies:
- python=3.9
- fiona=1.9.4
- geopandas=0.13.2
- mapbox_earcut=1.0.1
- pydeck=0.8.0
- topojson=1.7
- jupyter-book
- jupyterlab
- matplotlib
- numpy
- ghp-import
- pip
- pip:
  - triangle==20230923        #- python wrapper around Jonathan Richard Shewchuk's at rufat.be/triangle
  - cjio==0.7.3                                        #- python CLI to process and manipulate CityJSON files
  - overpass==0.7
  - osm2geojson==0.2.4
  - openlocationcode==1.0.1                            #- google 'plus codes' at https://github.com/google/open-location-code